--------------------------------------------------------
-- Archivo creado  - viernes-mayo-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "ADMINTM"."CLIENTE" 
   (	"ID_CLIENTE" NUMBER(*,0), 
	"NOMBRE_CLIENTE" VARCHAR2(35 BYTE), 
	"HABILITADO" CHAR(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FUNCION
--------------------------------------------------------

  CREATE TABLE "ADMINTM"."FUNCION" 
   (	"ID_FUNCION" NUMBER(*,0), 
	"UNIDAD_ID_UNIDAD" NUMBER(*,0), 
	"ID_TIPOFUNC" NUMBER(*,0), 
	"TIPO_FUNCION_ID_TIPOFUNC" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROBLEMA
--------------------------------------------------------

  CREATE TABLE "ADMINTM"."PROBLEMA" 
   (	"ID_PROBLEMA" NUMBER(*,0), 
	"COMENTARIO" VARCHAR2(255 BYTE), 
	"USUARIO_ID_USUARIO" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROCESO
--------------------------------------------------------

  CREATE TABLE "ADMINTM"."PROCESO" 
   (	"ID_PROCESO" NUMBER(*,0), 
	"TIPO_PROCESO" VARCHAR2(25 BYTE), 
	"CLIENTE_ID_CLIENTE" NUMBER(*,0), 
	"RESPONSABLE_ID_RESP" NUMBER(*,0), 
	"ID_RESPONSABLE" NUMBER(*,0), 
	"USUARIO_ID_USUARIO" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "ADMINTM"."ROL" 
   (	"ID_ROL" NUMBER(*,0), 
	"NOMBRE_ROL" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATUS_WORK
--------------------------------------------------------

  CREATE TABLE "ADMINTM"."STATUS_WORK" 
   (	"ID_STATUS" NUMBER(*,0), 
	"TIPO_STATUS" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAREA
--------------------------------------------------------

  CREATE TABLE "ADMINTM"."TAREA" 
   (	"ID_TAREA" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(420 BYTE), 
	"FECHA_INGRESO" DATE, 
	"FECHA_PLAZO" DATE, 
	"FECHA_RECEPCION" DATE, 
	"STATUS_WORK_ID_STATUS" NUMBER(*,0), 
	"FUNCION_ID_FUNCION" NUMBER(*,0), 
	"USUARIO_ID_USUARIO" NUMBER(*,0), 
	"ID_TSUPERIOR" NUMBER(*,0), 
	"ID_ANTES" NUMBER(*,0), 
	"ID_SUCES" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_FUNCION
--------------------------------------------------------

  CREATE TABLE "ADMINTM"."TIPO_FUNCION" 
   (	"ID_TIPOFUNC" NUMBER(*,0), 
	"PROCESO_ID_PROCESO" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UNIDAD
--------------------------------------------------------

  CREATE TABLE "ADMINTM"."UNIDAD" 
   (	"ID_UNIDAD" NUMBER(*,0), 
	"ID_PROCESO" NUMBER(*,0), 
	"TIPO_UNIDAD" VARCHAR2(35 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "ADMINTM"."USUARIO" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"CORREO" VARCHAR2(40 BYTE), 
	"HASH" VARCHAR2(60 BYTE), 
	"NOMBRE" VARCHAR2(35 BYTE), 
	"RUT" VARCHAR2(10 BYTE), 
	"DIRECCION" VARCHAR2(4000 BYTE), 
	"ROL_ID_ROL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ADMINTM.CLIENTE
SET DEFINE OFF;
REM INSERTING into ADMINTM.FUNCION
SET DEFINE OFF;
REM INSERTING into ADMINTM.PROBLEMA
SET DEFINE OFF;
REM INSERTING into ADMINTM.PROCESO
SET DEFINE OFF;
REM INSERTING into ADMINTM.ROL
SET DEFINE OFF;
Insert into ADMINTM.ROL (ID_ROL,NOMBRE_ROL) values ('2','Diseñador de Procesos');
Insert into ADMINTM.ROL (ID_ROL,NOMBRE_ROL) values ('3','Funcionario');
Insert into ADMINTM.ROL (ID_ROL,NOMBRE_ROL) values ('1','Administrador');
REM INSERTING into ADMINTM.STATUS_WORK
SET DEFINE OFF;
REM INSERTING into ADMINTM.TAREA
SET DEFINE OFF;
REM INSERTING into ADMINTM.TIPO_FUNCION
SET DEFINE OFF;
REM INSERTING into ADMINTM.UNIDAD
SET DEFINE OFF;
REM INSERTING into ADMINTM.USUARIO
SET DEFINE OFF;
Insert into ADMINTM.USUARIO (ID_USUARIO,CORREO,HASH,NOMBRE,RUT,DIRECCION,ROL_ID_ROL) values ('1','admin@taskmanager.com','1234','admin','11111111-1','central alerce','1');
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINTM"."CLIENTE_PK" ON "ADMINTM"."CLIENTE" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FUNCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINTM"."FUNCION_PK" ON "ADMINTM"."FUNCION" ("ID_FUNCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROBLEMA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINTM"."PROBLEMA_PK" ON "ADMINTM"."PROBLEMA" ("ID_PROBLEMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROCESO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINTM"."PROCESO_PK" ON "ADMINTM"."PROCESO" ("ID_PROCESO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINTM"."ROL_PK" ON "ADMINTM"."ROL" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STATUS_WORK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINTM"."STATUS_WORK_PK" ON "ADMINTM"."STATUS_WORK" ("ID_STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TAREA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINTM"."TAREA_PK" ON "ADMINTM"."TAREA" ("ID_TAREA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TIPO_FUNCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINTM"."TIPO_FUNCION_PK" ON "ADMINTM"."TIPO_FUNCION" ("ID_TIPOFUNC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UNIDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINTM"."UNIDAD_PK" ON "ADMINTM"."UNIDAD" ("ID_UNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINTM"."USUARIO_PK" ON "ADMINTM"."USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "ADMINTM"."CLIENTE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."CLIENTE" MODIFY ("NOMBRE_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."CLIENTE" MODIFY ("HABILITADO" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FUNCION
--------------------------------------------------------

  ALTER TABLE "ADMINTM"."FUNCION" MODIFY ("ID_FUNCION" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."FUNCION" MODIFY ("UNIDAD_ID_UNIDAD" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."FUNCION" MODIFY ("ID_TIPOFUNC" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."FUNCION" MODIFY ("TIPO_FUNCION_ID_TIPOFUNC" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."FUNCION" ADD CONSTRAINT "FUNCION_PK" PRIMARY KEY ("ID_FUNCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROBLEMA
--------------------------------------------------------

  ALTER TABLE "ADMINTM"."PROBLEMA" MODIFY ("ID_PROBLEMA" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."PROBLEMA" MODIFY ("COMENTARIO" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."PROBLEMA" MODIFY ("USUARIO_ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."PROBLEMA" ADD CONSTRAINT "PROBLEMA_PK" PRIMARY KEY ("ID_PROBLEMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROCESO
--------------------------------------------------------

  ALTER TABLE "ADMINTM"."PROCESO" MODIFY ("ID_PROCESO" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."PROCESO" MODIFY ("TIPO_PROCESO" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."PROCESO" MODIFY ("CLIENTE_ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."PROCESO" MODIFY ("RESPONSABLE_ID_RESP" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."PROCESO" MODIFY ("ID_RESPONSABLE" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."PROCESO" MODIFY ("USUARIO_ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."PROCESO" ADD CONSTRAINT "PROCESO_PK" PRIMARY KEY ("ID_PROCESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "ADMINTM"."ROL" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."ROL" MODIFY ("NOMBRE_ROL" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."ROL" ADD CONSTRAINT "ROL_PK" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATUS_WORK
--------------------------------------------------------

  ALTER TABLE "ADMINTM"."STATUS_WORK" MODIFY ("ID_STATUS" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."STATUS_WORK" MODIFY ("TIPO_STATUS" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."STATUS_WORK" ADD CONSTRAINT "STATUS_WORK_PK" PRIMARY KEY ("ID_STATUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TAREA
--------------------------------------------------------

  ALTER TABLE "ADMINTM"."TAREA" MODIFY ("ID_TAREA" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."TAREA" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."TAREA" MODIFY ("FECHA_INGRESO" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."TAREA" MODIFY ("FECHA_RECEPCION" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."TAREA" MODIFY ("STATUS_WORK_ID_STATUS" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."TAREA" MODIFY ("FUNCION_ID_FUNCION" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."TAREA" MODIFY ("USUARIO_ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."TAREA" ADD CONSTRAINT "TAREA_PK" PRIMARY KEY ("ID_TAREA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_FUNCION
--------------------------------------------------------

  ALTER TABLE "ADMINTM"."TIPO_FUNCION" MODIFY ("ID_TIPOFUNC" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."TIPO_FUNCION" MODIFY ("PROCESO_ID_PROCESO" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."TIPO_FUNCION" ADD CONSTRAINT "TIPO_FUNCION_PK" PRIMARY KEY ("ID_TIPOFUNC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UNIDAD
--------------------------------------------------------

  ALTER TABLE "ADMINTM"."UNIDAD" MODIFY ("ID_UNIDAD" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."UNIDAD" MODIFY ("ID_PROCESO" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."UNIDAD" MODIFY ("TIPO_UNIDAD" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."UNIDAD" ADD CONSTRAINT "UNIDAD_PK" PRIMARY KEY ("ID_UNIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "ADMINTM"."USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."USUARIO" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."USUARIO" MODIFY ("HASH" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."USUARIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."USUARIO" MODIFY ("RUT" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."USUARIO" MODIFY ("ROL_ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "ADMINTM"."USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FUNCION
--------------------------------------------------------

  ALTER TABLE "ADMINTM"."FUNCION" ADD CONSTRAINT "FUNCION_TIPO_FUNCION_FK" FOREIGN KEY ("TIPO_FUNCION_ID_TIPOFUNC")
	  REFERENCES "ADMINTM"."TIPO_FUNCION" ("ID_TIPOFUNC") ENABLE;
  ALTER TABLE "ADMINTM"."FUNCION" ADD CONSTRAINT "FUNCION_UNIDAD_FK" FOREIGN KEY ("UNIDAD_ID_UNIDAD")
	  REFERENCES "ADMINTM"."UNIDAD" ("ID_UNIDAD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROBLEMA
--------------------------------------------------------

  ALTER TABLE "ADMINTM"."PROBLEMA" ADD CONSTRAINT "PROBLEMA_USUARIO_FK" FOREIGN KEY ("USUARIO_ID_USUARIO")
	  REFERENCES "ADMINTM"."USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROCESO
--------------------------------------------------------

  ALTER TABLE "ADMINTM"."PROCESO" ADD CONSTRAINT "PROCESO_CLIENTE_FK" FOREIGN KEY ("CLIENTE_ID_CLIENTE")
	  REFERENCES "ADMINTM"."CLIENTE" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "ADMINTM"."PROCESO" ADD CONSTRAINT "PROCESO_USUARIO_FK" FOREIGN KEY ("USUARIO_ID_USUARIO")
	  REFERENCES "ADMINTM"."USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TAREA
--------------------------------------------------------

  ALTER TABLE "ADMINTM"."TAREA" ADD CONSTRAINT "TAREA_FUNCION_FK" FOREIGN KEY ("FUNCION_ID_FUNCION")
	  REFERENCES "ADMINTM"."FUNCION" ("ID_FUNCION") ENABLE;
  ALTER TABLE "ADMINTM"."TAREA" ADD CONSTRAINT "TAREA_STATUS_WORK_FK" FOREIGN KEY ("STATUS_WORK_ID_STATUS")
	  REFERENCES "ADMINTM"."STATUS_WORK" ("ID_STATUS") ENABLE;
  ALTER TABLE "ADMINTM"."TAREA" ADD CONSTRAINT "TAREA_USUARIO_FK" FOREIGN KEY ("USUARIO_ID_USUARIO")
	  REFERENCES "ADMINTM"."USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TIPO_FUNCION
--------------------------------------------------------

  ALTER TABLE "ADMINTM"."TIPO_FUNCION" ADD CONSTRAINT "TIPO_FUNCION_PROCESO_FK" FOREIGN KEY ("PROCESO_ID_PROCESO")
	  REFERENCES "ADMINTM"."PROCESO" ("ID_PROCESO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "ADMINTM"."USUARIO" ADD CONSTRAINT "USUARIO_ROL_FK" FOREIGN KEY ("ROL_ID_ROL")
	  REFERENCES "ADMINTM"."ROL" ("ID_ROL") ENABLE;
